### ISSUE TITLE
Race condition in aqua-analysis in weight generation

### ISSUE THREAD

**Issue by jhardenberg** [DestinE-Climate-DT/AQUA#1481]
### machine

Levante

### catalog

nextgems4

### version

None

### What happened?

In doing tests with aqua-analysis on levante (since lumi is offline these days) I got a new error for which some diagnostics may not run.
What happens is that both tropical precipitation and global means diagnostics for some reason decide to regrid the LRA data to the same grid (r100). This may be debatable and removed in future versions, but the problem is another one: 
when they start they both realize that on this machine the specific weight files for this transformation are missing and ... they try at the same time to reconstruct them (the diagnostics run in parallel threads and we have multiple instances of the diagnostic for different models running  at the same time). This is doomed to fail since there are two weight generation processes trying to write to the same file at the same time.

I am not sure how this could be solved. for me it highlights the risk also in the future that by chance (I admit you have to be unlucky) two instances of the workflow may try to access in write the same files at the same time  

### Error messages

2024-11-18 23:57:12 :: Reader :: WARNING  -> Weights file not found: /work/bb1153/b382075/aqua/weights/weights_IFS-FESOM_historical-1990_lra-r100-monthly_ycon_r100_l2d.nc
2024-11-18 23:57:12 :: Reader :: WARNING  -> Attempting to generate it ...
2024-11-18 23:57:12 :: Reader :: DEBUG    -> Grid size comparison - Original: 64800, New: 64800.
2024-11-18 23:57:12 :: Reader :: DEBUG    -> The total expected processing time is 0.5729823664707385 seconds.
Traceback (most recent call last):
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
           ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
            ~~~~~~~~~~~^^^^^
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('/work/bb1153/b382075/aqua/weights/weights_IFS-FESOM_historical-1990_lra-r100-monthly_ycon_r100_l2d.nc',), 'a', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False)), '5702da9d-5fd9-4306-9764-26654f2c2779']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/b/b382075/AQUA/diagnostics/tropical_rainfall/cli/cli_tropical_rainfall.py", line 51, in <module>
    main()
  File "/home/b/b382075/AQUA/diagnostics/tropical_rainfall/cli/cli_tropical_rainfall.py", line 40, in main
    trop_rainfall_cli = Tropical_Rainfall_CLI(config, args)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/AQUA/diagnostics/tropical_rainfall/cli/src/tropical_rainfall_cli_class.py", line 89, in __init__
    self.reader = Reader(model=self.model, exp=self.exp, source=self.source, loglevel=self.reader_loglevel, regrid=self.regrid,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/AQUA/src/aqua/reader/reader.py", line 217, in __init__
    self._load_generate_regrid_weights(cfg_regrid, rebuild)
  File "/home/b/b382075/AQUA/src/aqua/reader/reader.py", line 304, in _load_generate_regrid_weights
    self._make_weights_file(self.weightsfile[vc], source_grid,
  File "/home/b/b382075/AQUA/src/aqua/reader/regrid.py", line 189, in _make_weights_file
    weights.to_netcdf(weightsfile)
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/core/dataset.py", line 2338, in to_netcdf
    return to_netcdf(  # type: ignore[return-value]  # mypy cannot resolve the overloads:(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/backends/api.py", line 1403, in to_netcdf
    store = store_open(target, mode, format, group, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/backends/netCDF4_.py", line 410, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/backends/netCDF4_.py", line 357, in __init__
    self.format = self.ds.data_model
                  ^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/backends/netCDF4_.py", line 419, in ds
    return self._acquire()
           ^^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/backends/netCDF4_.py", line 413, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/backends/file_manager.py", line 199, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/netCDF4/_netCDF4.pyx", line 2470, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2107, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: '/work/bb1153/b382075/aqua/weights/weights_IFS-FESOM_historical-1990_lra-r100-monthly_ycon_r100_l2d.nc'
2024-11-18 23:57:24,321 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nosplit_nbytes_bin = await stream.read_bytes(fmt_size)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/distributed/worker.py", line 1269, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/distributed/utils_comm.py", line 441, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/distributed/utils_comm.py", line 420, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/distributed/core.py", line 1259, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/distributed/core.py", line 1018, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/home/b/b382075/mambaforge/envs/aqua/lib/python3.12/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:52792 remote=tcp://127.0.0.1:41179>: Stream is closed
[b382075@levante5 historical-1990]$ 


### Are you interested in making a pull request?

None

**Comment by jhardenberg** [comment]
So it turns out that if different diagnostics need to regrid, then we have this issue again and cli_checker is not solving it. 
Actually what we need is a `--regrid` option for `cli_checker`.... I will implement it.

**Comment by oloapinivad** [comment]
We discussed that a potential solution is to create a lockfile on the AQUA side, and then if the file is found wait for a moderate amount of time (30 sec). If after this the lockfile is still there, fail with ad hoc error. If rebuild=true the lockfile should be removed and ignored.

**Comment by jhardenberg** [comment]
indeed @mnurisso @oloapinivad I have now run again into this problem:
when I run multiple aqua-analysis at  the same time (because I may have multiple experiments to analyse), `setup_checker` is run for all of them. Since it also rebuilds weights and areas, what can happen is that a new aqua-analysis deiced to rebuold weights and areas exaclty while another instance is using them .... again leading to disaster

**Comment by jhardenberg** [comment]
Ok, the writing/reading race is actually easy to solve: write always to a temporary filename and then replce with `os.replace()` once ready, This way another utility cannot by chance read a half-ready file. When generating the files instead we could either lock them or simply use the same approach (this may be better). No locks needed.
The other problem we had was different because we needd to integrate different info into the yaml files. There a lock is needed. But if we are dealing with multiple processes reconstructing weights or area files, it should be enough to pay attention newer to write dorectly to the files and always go through a temp file.
